#include "dbus_accessor.hpp"

#include <cassert>

#include "gmock/gmock.h"
using namespace testing;

class DummyObjectMapper : public dbus::ObjectMapper<DummyObjectMapper>
{

  public:
    std::vector<std::string>
        getSubTreePathsImpl(sdbusplus::bus::bus& bus,
                            const std::string& subtree, int depth,
                            const std::vector<std::string>& interfaces);
};

std::vector<std::string> DummyObjectMapper::getSubTreePathsImpl(
    [[maybe_unused]] sdbusplus::bus::bus& bus,
    [[maybe_unused]] const std::string& subtree, [[maybe_unused]] int depth,
    [[maybe_unused]] const std::vector<std::string>& interfaces)
{
    assert(depth == 0);
    assert(subtree == "/");
    std::vector<std::string> result;
    result.push_back("/");
    result.push_back("/xyz");
    result.push_back("/xyz/openbmc_project");
    result.push_back("/xyz/openbmc_project/GpuMgr");
    result.push_back("/xyz/openbmc_project/inventory");
    result.push_back("/xyz/openbmc_project/inventory/platformmetrics");
    result.push_back("/xyz/openbmc_project/inventory/system");
    result.push_back("/xyz/openbmc_project/inventory/system/chassis");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_Chassis_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_Chassis_0/Assembly0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_Chassis_0/Assembly1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_Chassis_0/Assembly2");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_Chassis_0/PCIeSlots0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_Chassis_0/PCIeSlots1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_Chassis_0/PCIeSlots2");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_Chassis_0/PCIeSlots3");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_Chassis_0/PCIeSlots4");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_Chassis_0/PCIeSlots5");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_Chassis_0/PCIeSlots6");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_Chassis_0/PCIeSlots7");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_Chassis_0/PCIeSlots8");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_Chassis_0/PCIeSlots9");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_FPGA_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_1/Assembly0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_1/Assembly1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_1/PCIeDevices");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_1/PCIeDevices/GPU_SXM_1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_2");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_2/Assembly0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_2/Assembly1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_2/PCIeDevices");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_2/PCIeDevices/GPU_SXM_2");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_3");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_3/Assembly0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_3/Assembly1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_3/PCIeDevices");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_3/PCIeDevices/GPU_SXM_3");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_4");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_4/Assembly0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_4/Assembly1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_4/PCIeDevices");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_4/PCIeDevices/GPU_SXM_4");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_5");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_5/Assembly0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_5/Assembly1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_5/PCIeDevices");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_5/PCIeDevices/GPU_SXM_5");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_6");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_6/Assembly0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_6/Assembly1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_6/PCIeDevices");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_6/PCIeDevices/GPU_SXM_6");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_7");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_7/Assembly0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_7/Assembly1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_7/PCIeDevices");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_7/PCIeDevices/GPU_SXM_7");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_8");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_8/Assembly0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_8/Assembly1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_8/PCIeDevices");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_8/PCIeDevices/GPU_SXM_8");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_NVSwitch_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_NVSwitch_0/PCIeDevices");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_NVSwitch_0/PCIeDevices/NVSwitch_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_NVSwitch_1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_NVSwitch_1/PCIeDevices");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_NVSwitch_1/PCIeDevices/NVSwitch_1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_NVSwitch_2");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_NVSwitch_2/PCIeDevices");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_NVSwitch_2/PCIeDevices/NVSwitch_2");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_NVSwitch_3");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_NVSwitch_3/PCIeDevices");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_NVSwitch_3/PCIeDevices/NVSwitch_3");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_PCIeRetimer_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_PCIeRetimer_1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_PCIeRetimer_2");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_PCIeRetimer_3");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_PCIeRetimer_4");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_PCIeRetimer_5");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_PCIeRetimer_6");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_PCIeRetimer_7");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_PCIeSwitch_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_PCIeSwitch_0/PCIeDevices");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/chassis/HGX_PCIeSwitch_0/PCIeDevices/PCIeSwitch_0");
    result.push_back("/xyz/openbmc_project/inventory/system/fabrics");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Endpoints");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Endpoints/GPU_SXM_1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Endpoints/GPU_SXM_2");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Endpoints/GPU_SXM_3");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Endpoints/GPU_SXM_4");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Endpoints/GPU_SXM_5");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Endpoints/GPU_SXM_6");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Endpoints/GPU_SXM_7");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Endpoints/GPU_SXM_8");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_10");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_11");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_12");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_13");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_14");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_15");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_16");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_17");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_18");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_19");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_2");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_20");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_21");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_22");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_23");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_24");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_25");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_26");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_27");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_28");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_29");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_3");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_30");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_31");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_4");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_5");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_6");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_7");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_8");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_0/Ports/NVLink_9");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_10");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_11");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_12");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_13");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_14");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_15");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_16");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_17");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_18");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_19");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_2");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_20");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_21");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_22");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_23");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_24");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_25");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_26");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_27");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_28");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_29");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_3");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_30");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_31");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_32");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_33");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_34");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_35");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_36");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_37");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_38");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_39");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_4");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_5");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_6");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_7");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_8");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_1/Ports/NVLink_9");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_10");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_11");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_12");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_13");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_14");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_15");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_16");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_17");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_18");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_19");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_2");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_20");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_21");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_22");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_23");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_24");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_25");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_26");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_27");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_28");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_29");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_3");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_30");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_31");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_32");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_33");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_34");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_35");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_36");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_37");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_38");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_39");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_4");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_5");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_6");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_7");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_8");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_2/Ports/NVLink_9");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_10");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_11");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_12");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_13");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_14");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_15");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_16");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_17");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_18");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_19");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_2");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_20");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_21");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_22");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_23");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_24");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_25");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_26");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_27");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_28");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_29");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_3");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_30");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_31");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_4");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_5");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_6");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_7");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_8");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Switches/NVSwitch_3/Ports/NVLink_9");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/zones");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/zones/0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_0/Endpoints");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_0/Endpoints/GPU_SXM_1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_0/Switches");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_0/Switches/PCIeRetimer_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_0/Switches/PCIeRetimer_0/Ports");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_0/Switches/PCIeRetimer_0/Ports/DOWN_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_0/Switches/PCIeRetimer_0/Ports/UP_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_0/zones");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_0/zones/0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_1/Endpoints");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_1/Endpoints/GPU_SXM_2");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_1/Switches");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_1/Switches/PCIeRetimer_1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_1/Switches/PCIeRetimer_1/Ports");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_1/Switches/PCIeRetimer_1/Ports/DOWN_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_1/Switches/PCIeRetimer_1/Ports/UP_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_1/zones");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_1/zones/0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_2");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_2/Endpoints");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_2/Endpoints/GPU_SXM_3");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_2/Switches");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_2/Switches/PCIeRetimer_2");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_2/Switches/PCIeRetimer_2/Ports");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_2/Switches/PCIeRetimer_2/Ports/DOWN_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_2/Switches/PCIeRetimer_2/Ports/UP_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_2/zones");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_2/zones/0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_3");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_3/Endpoints");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_3/Endpoints/GPU_SXM_4");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_3/Switches");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_3/Switches/PCIeRetimer_3");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_3/Switches/PCIeRetimer_3/Ports");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_3/Switches/PCIeRetimer_3/Ports/DOWN_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_3/Switches/PCIeRetimer_3/Ports/UP_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_3/zones");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_3/zones/0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_4");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_4/Endpoints");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_4/Endpoints/GPU_SXM_5");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_4/Switches");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_4/Switches/PCIeRetimer_4");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_4/Switches/PCIeRetimer_4/Ports");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_4/Switches/PCIeRetimer_4/Ports/DOWN_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_4/Switches/PCIeRetimer_4/Ports/UP_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_4/zones");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_4/zones/0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_5");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_5/Endpoints");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_5/Endpoints/GPU_SXM_6");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_5/Switches");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_5/Switches/PCIeRetimer_5");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_5/Switches/PCIeRetimer_5/Ports");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_5/Switches/PCIeRetimer_5/Ports/DOWN_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_5/Switches/PCIeRetimer_5/Ports/UP_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_5/zones");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_5/zones/0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_6");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_6/Endpoints");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_6/Endpoints/GPU_SXM_7");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_6/Switches");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_6/Switches/PCIeRetimer_6");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_6/Switches/PCIeRetimer_6/Ports");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_6/Switches/PCIeRetimer_6/Ports/DOWN_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_6/Switches/PCIeRetimer_6/Ports/UP_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_6/zones");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_6/zones/0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_7");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_7/Endpoints");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_7/Endpoints/GPU_SXM_8");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_7/Switches");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_7/Switches/PCIeRetimer_7");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_7/Switches/PCIeRetimer_7/Ports");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_7/Switches/PCIeRetimer_7/Ports/DOWN_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_7/Switches/PCIeRetimer_7/Ports/UP_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_7/zones");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_7/zones/0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeSwitchTopology_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeSwitchTopology_0/Endpoints");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeSwitchTopology_0/Endpoints/NVSwitch_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeSwitchTopology_0/Endpoints/NVSwitch_1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeSwitchTopology_0/Endpoints/NVSwitch_2");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeSwitchTopology_0/Endpoints/NVSwitch_3");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeSwitchTopology_0/Switches");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeSwitchTopology_0/Switches/PCIeSwitch_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeSwitchTopology_0/Switches/PCIeSwitch_0/Ports");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeSwitchTopology_0/Switches/PCIeSwitch_0/Ports/DOWN_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeSwitchTopology_0/Switches/PCIeSwitch_0/Ports/DOWN_1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeSwitchTopology_0/Switches/PCIeSwitch_0/Ports/DOWN_2");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeSwitchTopology_0/Switches/PCIeSwitch_0/Ports/DOWN_3");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeSwitchTopology_0/Switches/PCIeSwitch_0/Ports/UP_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeSwitchTopology_0/zones");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeSwitchTopology_0/zones/0");
    result.push_back("/xyz/openbmc_project/inventory/system/managers");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/managers/HGX_FabricManager_0");
    result.push_back("/xyz/openbmc_project/inventory/system/memory");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/memory/GPU_SXM_1_DRAM_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/memory/GPU_SXM_2_DRAM_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/memory/GPU_SXM_3_DRAM_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/memory/GPU_SXM_4_DRAM_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/memory/GPU_SXM_5_DRAM_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/memory/GPU_SXM_6_DRAM_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/memory/GPU_SXM_7_DRAM_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/memory/GPU_SXM_8_DRAM_0");
    result.push_back("/xyz/openbmc_project/inventory/system/processors");
    result.push_back("/xyz/openbmc_project/inventory/system/processors/FPGA_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/FPGA_0/Ports");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/FPGA_0/Ports/PCIeToHMC_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/FPGA_0/Ports/PCIeToHost_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_1/Ports");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_1/Ports/NVLink_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_1/Ports/NVLink_1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_1/Ports/NVLink_10");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_1/Ports/NVLink_11");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_1/Ports/NVLink_12");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_1/Ports/NVLink_13");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_1/Ports/NVLink_14");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_1/Ports/NVLink_15");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_1/Ports/NVLink_16");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_1/Ports/NVLink_17");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_1/Ports/NVLink_2");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_1/Ports/NVLink_3");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_1/Ports/NVLink_4");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_1/Ports/NVLink_5");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_1/Ports/NVLink_6");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_1/Ports/NVLink_7");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_1/Ports/NVLink_8");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_1/Ports/NVLink_9");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_2");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_2/Ports");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_2/Ports/NVLink_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_2/Ports/NVLink_1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_2/Ports/NVLink_10");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_2/Ports/NVLink_11");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_2/Ports/NVLink_12");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_2/Ports/NVLink_13");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_2/Ports/NVLink_14");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_2/Ports/NVLink_15");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_2/Ports/NVLink_16");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_2/Ports/NVLink_17");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_2/Ports/NVLink_2");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_2/Ports/NVLink_3");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_2/Ports/NVLink_4");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_2/Ports/NVLink_5");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_2/Ports/NVLink_6");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_2/Ports/NVLink_7");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_2/Ports/NVLink_8");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_2/Ports/NVLink_9");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_3");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_3/Ports");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_3/Ports/NVLink_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_3/Ports/NVLink_1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_3/Ports/NVLink_10");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_3/Ports/NVLink_11");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_3/Ports/NVLink_12");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_3/Ports/NVLink_13");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_3/Ports/NVLink_14");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_3/Ports/NVLink_15");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_3/Ports/NVLink_16");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_3/Ports/NVLink_17");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_3/Ports/NVLink_2");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_3/Ports/NVLink_3");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_3/Ports/NVLink_4");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_3/Ports/NVLink_5");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_3/Ports/NVLink_6");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_3/Ports/NVLink_7");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_3/Ports/NVLink_8");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_3/Ports/NVLink_9");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_4");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_4/Ports");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_4/Ports/NVLink_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_4/Ports/NVLink_1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_4/Ports/NVLink_10");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_4/Ports/NVLink_11");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_4/Ports/NVLink_12");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_4/Ports/NVLink_13");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_4/Ports/NVLink_14");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_4/Ports/NVLink_15");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_4/Ports/NVLink_16");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_4/Ports/NVLink_17");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_4/Ports/NVLink_2");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_4/Ports/NVLink_3");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_4/Ports/NVLink_4");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_4/Ports/NVLink_5");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_4/Ports/NVLink_6");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_4/Ports/NVLink_7");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_4/Ports/NVLink_8");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_4/Ports/NVLink_9");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_5");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_5/Ports");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_5/Ports/NVLink_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_5/Ports/NVLink_1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_5/Ports/NVLink_10");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_5/Ports/NVLink_11");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_5/Ports/NVLink_12");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_5/Ports/NVLink_13");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_5/Ports/NVLink_14");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_5/Ports/NVLink_15");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_5/Ports/NVLink_16");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_5/Ports/NVLink_17");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_5/Ports/NVLink_2");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_5/Ports/NVLink_3");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_5/Ports/NVLink_4");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_5/Ports/NVLink_5");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_5/Ports/NVLink_6");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_5/Ports/NVLink_7");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_5/Ports/NVLink_8");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_5/Ports/NVLink_9");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_6");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_6/Ports");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_6/Ports/NVLink_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_6/Ports/NVLink_1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_6/Ports/NVLink_10");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_6/Ports/NVLink_11");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_6/Ports/NVLink_12");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_6/Ports/NVLink_13");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_6/Ports/NVLink_14");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_6/Ports/NVLink_15");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_6/Ports/NVLink_16");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_6/Ports/NVLink_17");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_6/Ports/NVLink_2");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_6/Ports/NVLink_3");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_6/Ports/NVLink_4");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_6/Ports/NVLink_5");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_6/Ports/NVLink_6");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_6/Ports/NVLink_7");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_6/Ports/NVLink_8");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_6/Ports/NVLink_9");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_7");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_7/Ports");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_7/Ports/NVLink_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_7/Ports/NVLink_1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_7/Ports/NVLink_10");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_7/Ports/NVLink_11");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_7/Ports/NVLink_12");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_7/Ports/NVLink_13");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_7/Ports/NVLink_14");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_7/Ports/NVLink_15");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_7/Ports/NVLink_16");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_7/Ports/NVLink_17");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_7/Ports/NVLink_2");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_7/Ports/NVLink_3");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_7/Ports/NVLink_4");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_7/Ports/NVLink_5");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_7/Ports/NVLink_6");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_7/Ports/NVLink_7");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_7/Ports/NVLink_8");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_7/Ports/NVLink_9");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_8");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_8/Ports");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_8/Ports/NVLink_0");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_8/Ports/NVLink_1");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_8/Ports/NVLink_10");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_8/Ports/NVLink_11");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_8/Ports/NVLink_12");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_8/Ports/NVLink_13");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_8/Ports/NVLink_14");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_8/Ports/NVLink_15");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_8/Ports/NVLink_16");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_8/Ports/NVLink_17");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_8/Ports/NVLink_2");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_8/Ports/NVLink_3");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_8/Ports/NVLink_4");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_8/Ports/NVLink_5");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_8/Ports/NVLink_6");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_8/Ports/NVLink_7");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_8/Ports/NVLink_8");
    result.push_back(
        "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_8/Ports/NVLink_9");
    result.push_back("/xyz/openbmc_project/inventory/system/system");
    result.push_back("/xyz/openbmc_project/inventory/system/system/system0");
    result.push_back("/xyz/openbmc_project/inventory_software");
    result.push_back(
        "/xyz/openbmc_project/inventory_software/HGX_Driver_GPU_SXM_1");
    result.push_back(
        "/xyz/openbmc_project/inventory_software/HGX_Driver_GPU_SXM_2");
    result.push_back(
        "/xyz/openbmc_project/inventory_software/HGX_Driver_GPU_SXM_3");
    result.push_back(
        "/xyz/openbmc_project/inventory_software/HGX_Driver_GPU_SXM_4");
    result.push_back(
        "/xyz/openbmc_project/inventory_software/HGX_Driver_GPU_SXM_5");
    result.push_back(
        "/xyz/openbmc_project/inventory_software/HGX_Driver_GPU_SXM_6");
    result.push_back(
        "/xyz/openbmc_project/inventory_software/HGX_Driver_GPU_SXM_7");
    result.push_back(
        "/xyz/openbmc_project/inventory_software/HGX_Driver_GPU_SXM_8");
    result.push_back(
        "/xyz/openbmc_project/inventory_software/HGX_Driver_NVSwitch_0");
    result.push_back(
        "/xyz/openbmc_project/inventory_software/HGX_Driver_NVSwitch_1");
    result.push_back(
        "/xyz/openbmc_project/inventory_software/HGX_Driver_NVSwitch_2");
    result.push_back(
        "/xyz/openbmc_project/inventory_software/HGX_Driver_NVSwitch_3");
    result.push_back("/xyz/openbmc_project/sensors");
    result.push_back("/xyz/openbmc_project/sensors/altitude");
    result.push_back(
        "/xyz/openbmc_project/sensors/altitude/HGX_Chassis_0_AltitudePressure_0");
    result.push_back("/xyz/openbmc_project/sensors/energy");
    result.push_back(
        "/xyz/openbmc_project/sensors/energy/HGX_GPU_SXM_1_Energy_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/energy/HGX_GPU_SXM_2_Energy_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/energy/HGX_GPU_SXM_3_Energy_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/energy/HGX_GPU_SXM_4_Energy_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/energy/HGX_GPU_SXM_5_Energy_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/energy/HGX_GPU_SXM_6_Energy_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/energy/HGX_GPU_SXM_7_Energy_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/energy/HGX_GPU_SXM_8_Energy_0");
    result.push_back("/xyz/openbmc_project/sensors/power");
    result.push_back(
        "/xyz/openbmc_project/sensors/power/HGX_Chassis_0_HSC_0_Power_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/power/HGX_Chassis_0_HSC_1_Power_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/power/HGX_Chassis_0_HSC_2_Power_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/power/HGX_Chassis_0_HSC_3_Power_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/power/HGX_Chassis_0_HSC_4_Power_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/power/HGX_Chassis_0_HSC_5_Power_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/power/HGX_Chassis_0_HSC_6_Power_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/power/HGX_Chassis_0_HSC_7_Power_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/power/HGX_Chassis_0_HSC_8_Power_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/power/HGX_Chassis_0_HSC_9_Power_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/power/HGX_Chassis_0_StandbyHSC_0_Power_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/power/HGX_Chassis_0_TotalGPU_Power_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/power/HGX_Chassis_0_TotalHSC_Power_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/power/HGX_GPU_SXM_1_DRAM_0_Power_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/power/HGX_GPU_SXM_1_Power_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/power/HGX_GPU_SXM_2_DRAM_0_Power_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/power/HGX_GPU_SXM_2_Power_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/power/HGX_GPU_SXM_3_DRAM_0_Power_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/power/HGX_GPU_SXM_3_Power_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/power/HGX_GPU_SXM_4_DRAM_0_Power_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/power/HGX_GPU_SXM_4_Power_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/power/HGX_GPU_SXM_5_DRAM_0_Power_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/power/HGX_GPU_SXM_5_Power_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/power/HGX_GPU_SXM_6_DRAM_0_Power_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/power/HGX_GPU_SXM_6_Power_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/power/HGX_GPU_SXM_7_DRAM_0_Power_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/power/HGX_GPU_SXM_7_Power_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/power/HGX_GPU_SXM_8_DRAM_0_Power_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/power/HGX_GPU_SXM_8_Power_0");
    result.push_back("/xyz/openbmc_project/sensors/temperature");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_Chassis_0_HSC_0_Temp_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_Chassis_0_HSC_1_Temp_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_Chassis_0_HSC_2_Temp_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_Chassis_0_HSC_3_Temp_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_Chassis_0_HSC_4_Temp_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_Chassis_0_HSC_5_Temp_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_Chassis_0_HSC_6_Temp_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_Chassis_0_HSC_7_Temp_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_Chassis_0_HSC_8_Temp_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_Chassis_0_HSC_9_Temp_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_Chassis_0_Inlet_0_Temp_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_Chassis_0_Inlet_1_Temp_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_Chassis_0_PCB_0_Temp_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_Chassis_0_PCB_1_Temp_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_Chassis_0_PCB_2_Temp_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_Chassis_0_PCB_3_Temp_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_Chassis_0_StandbyHSC_0_Temp_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_FPGA_0_TEMP_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_GPU_SXM_1_DRAM_0_Temp_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_GPU_SXM_1_TEMP_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_GPU_SXM_2_DRAM_0_Temp_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_GPU_SXM_2_TEMP_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_GPU_SXM_3_DRAM_0_Temp_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_GPU_SXM_3_TEMP_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_GPU_SXM_4_DRAM_0_Temp_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_GPU_SXM_4_TEMP_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_GPU_SXM_5_DRAM_0_Temp_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_GPU_SXM_5_TEMP_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_GPU_SXM_6_DRAM_0_Temp_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_GPU_SXM_6_TEMP_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_GPU_SXM_7_DRAM_0_Temp_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_GPU_SXM_7_TEMP_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_GPU_SXM_8_DRAM_0_Temp_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_GPU_SXM_8_TEMP_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_NVSwitch_0_TEMP_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_NVSwitch_1_TEMP_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_NVSwitch_2_TEMP_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_NVSwitch_3_TEMP_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_PCIeRetimer_0_TEMP_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_PCIeRetimer_1_TEMP_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_PCIeRetimer_2_TEMP_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_PCIeRetimer_3_TEMP_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_PCIeRetimer_4_TEMP_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_PCIeRetimer_5_TEMP_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_PCIeRetimer_6_TEMP_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_PCIeRetimer_7_TEMP_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/temperature/HGX_PCIeSwitch_0_TEMP_0");
    result.push_back("/xyz/openbmc_project/sensors/voltage");
    result.push_back(
        "/xyz/openbmc_project/sensors/voltage/HGX_GPU_SXM_1_Voltage_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/voltage/HGX_GPU_SXM_2_Voltage_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/voltage/HGX_GPU_SXM_3_Voltage_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/voltage/HGX_GPU_SXM_4_Voltage_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/voltage/HGX_GPU_SXM_5_Voltage_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/voltage/HGX_GPU_SXM_6_Voltage_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/voltage/HGX_GPU_SXM_7_Voltage_0");
    result.push_back(
        "/xyz/openbmc_project/sensors/voltage/HGX_GPU_SXM_8_Voltage_0");
    result.push_back("/xyz/openbmc_project/software");
    result.push_back("/xyz/openbmc_project/software/HGX_FW_FPGA_0");
    result.push_back("/xyz/openbmc_project/software/HGX_FW_GPU_SXM_1");
    result.push_back("/xyz/openbmc_project/software/HGX_FW_GPU_SXM_2");
    result.push_back("/xyz/openbmc_project/software/HGX_FW_GPU_SXM_3");
    result.push_back("/xyz/openbmc_project/software/HGX_FW_GPU_SXM_4");
    result.push_back("/xyz/openbmc_project/software/HGX_FW_GPU_SXM_5");
    result.push_back("/xyz/openbmc_project/software/HGX_FW_GPU_SXM_6");
    result.push_back("/xyz/openbmc_project/software/HGX_FW_GPU_SXM_7");
    result.push_back("/xyz/openbmc_project/software/HGX_FW_GPU_SXM_8");
    result.push_back("/xyz/openbmc_project/software/HGX_FW_NVSwitch_0");
    result.push_back("/xyz/openbmc_project/software/HGX_FW_NVSwitch_1");
    result.push_back("/xyz/openbmc_project/software/HGX_FW_NVSwitch_2");
    result.push_back("/xyz/openbmc_project/software/HGX_FW_NVSwitch_3");
    result.push_back("/xyz/openbmc_project/software/HGX_FW_PCIeRetimer_0");
    result.push_back("/xyz/openbmc_project/software/HGX_FW_PCIeRetimer_1");
    result.push_back("/xyz/openbmc_project/software/HGX_FW_PCIeRetimer_2");
    result.push_back("/xyz/openbmc_project/software/HGX_FW_PCIeRetimer_3");
    result.push_back("/xyz/openbmc_project/software/HGX_FW_PCIeRetimer_4");
    result.push_back("/xyz/openbmc_project/software/HGX_FW_PCIeRetimer_5");
    result.push_back("/xyz/openbmc_project/software/HGX_FW_PCIeRetimer_6");
    result.push_back("/xyz/openbmc_project/software/HGX_FW_PCIeRetimer_7");
    result.push_back("/xyz/openbmc_project/software/HGX_FW_PCIeSwitch_0");
    result.push_back("/xyz/openbmc_project/software/HGX_InfoROM_GPU_SXM_1");
    result.push_back("/xyz/openbmc_project/software/HGX_InfoROM_GPU_SXM_2");
    result.push_back("/xyz/openbmc_project/software/HGX_InfoROM_GPU_SXM_3");
    result.push_back("/xyz/openbmc_project/software/HGX_InfoROM_GPU_SXM_4");
    result.push_back("/xyz/openbmc_project/software/HGX_InfoROM_GPU_SXM_5");
    result.push_back("/xyz/openbmc_project/software/HGX_InfoROM_GPU_SXM_6");
    result.push_back("/xyz/openbmc_project/software/HGX_InfoROM_GPU_SXM_7");
    result.push_back("/xyz/openbmc_project/software/HGX_InfoROM_GPU_SXM_8");
    result.push_back("/xyz/openbmc_project/software/HGX_InfoROM_NVSwitch_0");
    result.push_back("/xyz/openbmc_project/software/HGX_InfoROM_NVSwitch_1");
    result.push_back("/xyz/openbmc_project/software/HGX_InfoROM_NVSwitch_2");
    result.push_back("/xyz/openbmc_project/software/HGX_InfoROM_NVSwitch_3");
    return result;
}

TEST(ObjectMapper, getAllDevIdObjPaths)
{
    DummyObjectMapper om;
    EXPECT_THAT(
        om.getAllDevIdObjPaths("GPU_SXM_3"),
        UnorderedElementsAre(
            "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_3",
            "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_3/PCIeDevices/GPU_SXM_3",
            "/xyz/openbmc_project/inventory/system/fabrics/HGX_NVLinkFabric_0/Endpoints/GPU_SXM_3",
            "/xyz/openbmc_project/inventory/system/fabrics/HGX_PCIeRetimerTopology_2/Endpoints/GPU_SXM_3",
            "/xyz/openbmc_project/inventory/system/processors/GPU_SXM_3"));
}

TEST(ObjectMapper, getPrimaryDevIdPaths)
{
    DummyObjectMapper om;
    EXPECT_THAT(
        om.getPrimaryDevIdPaths("GPU_SXM_3"),
        UnorderedElementsAre(
            "/xyz/openbmc_project/inventory/system/chassis/HGX_GPU_SXM_3"));
}

TEST(ObjectMapper, getPrimaryDevIdPaths1)
{
    DummyObjectMapper om;
    EXPECT_THAT(
        om.getPrimaryDevIdPaths("PCIeSwitch_0"),
        UnorderedElementsAre(
            "/xyz/openbmc_project/inventory/system/chassis/HGX_PCIeSwitch_0"));
}
