#!/usr/bin/env bash

# Copyright (c) 2023, NVIDIA CORPORATION.  All rights reserved.
#
#  NVIDIA CORPORATION and its licensors retain all intellectual property
#  and proprietary rights in and to this software, related documentation
#  and any modifications thereto.  Any use, reproduction, disclosure or
#  distribution of this software and related documentation without an express
#  license agreement from NVIDIA CORPORATION is strictly prohibited.

# Simple wrapper to 'mctp-vdm-util-wrapper' to map 'device name' to 'device id'
# and prettier cmd support.

set -o pipefail

APP_NAME="aml-memory-watcher"
APP_VER="0.1"

[ -z "$PROCESS_NAME" ] && PROCESS_NAME="oobamld"
[ -z "$SERVICE_NAME" ] && SERVICE_NAME="nvidia-oobaml.service"
[ -z "$MEMORY_LIMIT_MB" ] && MEMORY_LIMIT_MB=500
[ -z "$RESTART_DELAY" ] && RESTART_DELAY=5
[ -z "$CHECK_INTERVAL" ] && CHECK_INTERVAL=60

memory_limit_kb=$((MEMORY_LIMIT_MB * 1024))
while true; do
    pgrep -x "$PROCESS_NAME" | while read -r pid; do
        #echo "$PROCESS_NAME pid: $pid"
        vmsize=$(grep 'VmSize' "/proc/$pid/status" | awk '{print $2}')
        #echo "$PROCESS_NAME VSIZE (KB): $vmsize"
        if [ "$vmsize" -gt "$memory_limit_kb" ]; then
            echo "<3>$PROCESS_NAME memory limit exceeded ($vmsize KB > $memory_limit_kb KB)"
            kill -9 "$pid"
            sleep "$RESTART_DELAY"
            # if not already restarted by this time, restart service manually
            systemctl reset-failed "$SERVICE_NAME"
            systemctl start "$SERVICE_NAME"
        fi
    done

    sleep "$CHECK_INTERVAL"
done
